# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Create custom jobs to be used in workflow
jobs:
  # This job prints "Hello" to stdout
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout # this pulls code from GitHub
      - run: echo "Hello" # this prints "Hello" to stdout
  # This job prints your name to stdout using env variable
  print_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout # this pulls code from GitHub
      - run: 
          name: "Set a custom env variable"
          command: |
            MY_NAME="Olga Lyudchik"
            echo $MY_NAME
  # This job saves Hello World to the file and shares that file with another jobs via workspace
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout # this pulls code from GitHub
      - run: 
          name: "Save Hello World to output.txt"
          command: echo "Hello World" > ~/output.txt # this saves "Hello World" to the file output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  # This job prints the content of shared file
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout # this pulls code from GitHub
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt # this print content of the output.txt to stdout
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the greeting jobs in their own containers
    jobs:
      - print_hello
      - print_name:
          requires:
            - print_hello
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output