# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Create custom jobs to be used in workflow
jobs:
  # This job prints "Hello" to stdout
  print_hello:
    # It uses the docker executor
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout # this pulls code from GitHub
      - run: echo "Hello" # this prints "Hello" to stdout
  # This job prints "World" to stdout
  print_world:
    # It uses the docker executor
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout # this pulls code from GitHub
      - run: echo "World" # this prints "World" to stdout  
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
